##  Indexing And Slicing

First we import numpy library like this:

In [1]:
import numpy as np

We create a one dimensional numpy array using arange() function like this: 

In [2]:
array = np.arange(2,20,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

To slice the fifth element:

In [3]:
array[4]

10

To slice a range of elements from the third to the eighth element:

In [4]:
array[2:8]

array([ 6,  8, 10, 12, 14, 16])

To slice for the begining, we leave the start before the colon empty:

In [5]:
array[:6]

array([ 2,  4,  6,  8, 10, 12])

To slice to the end, we leave the end after the colon empty:

In [6]:
array[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

To slice the whole array we use only the colon:

In [7]:
array[:]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

To show that the slice is a mirror, not a copy, lets first assign the slice to a new array like this:

In [8]:
slice1 = array[2:6]
slice1

array([ 6,  8, 10, 12])

Now we change the first element to number 99:

In [9]:
slice1[0] = 78
slice1

array([78,  8, 10, 12])

Lets display the original array, to see if it is changed when the slice is changed.

In [10]:
array

array([ 2,  4, 78,  8, 10, 12, 14, 16, 18])

To make the slice a copy not a mirror we use the function copy()

In [11]:
slice2= array[2:5].copy()
slice2

array([78,  8, 10])

Here we creat 4 by 3 array using a nested list:

In [12]:
array2d = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
array2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

To slice a two-dimentional array, we use two colons, one for rows and one for columns:

In [13]:
array2d[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

If we use one colon, python recognize it for the rows

In [14]:
array2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

Here we use a bare colon to select all rows:

In [15]:
array2d[:,1]

array([ 2,  5,  8, 11])

We can select a range of rows and a range of columns like this:

In [16]:
array2d[1:3, 1:4]

array([[5, 6],
       [8, 9]])

Without colons, a single row or a single colum can be selected like this

In [17]:
array2d[2,1]

8

***

<h1 align="center">Thank You(Day 5 of 30)</h1> 

***