 # Creating Ndarrays(Numpy Arrays)

First of all I will import the numpy library for the execution to run

In [1]:
import numpy as np

I will create a numpy array using the function in python known as random.randn() from numpy library I imported above

In [2]:
first_array = np.random.randn(2,3)
first_array

array([[-0.70717005,  1.23931414,  0.76047009],
       [ 0.47432649,  0.15767869,  0.32571517]])

Now lets check the dimension of the first_array by using the attribute .ndim

In [3]:
first_array.ndim

2

Now lets check the shape of the first_array by using the attribute.shape

In [4]:
first_array.shape

(2, 3)

To check the Data type of the first_array we use the attribute dtype

In [5]:
first_array.dtype

dtype('float64')

 I will  create a list 

In [6]:
first_list = [5,7,8,0,3,2,1]

I will convert this list into numpy array using the numpy array() function and display it

In [7]:
second_array = np.array(first_list)
second_array

array([5, 7, 8, 0, 3, 2, 1])

Now lets check the dimension using the 'ndim' attribute

In [8]:
second_array.ndim

1

Now, lets check the shape using the shape attribute

In [9]:
second_array.shape


(7,)

Now, lets create a nested list

In [10]:
second_list = [[2,3,4],[5,6,7]]

Now we convert the second_list into numpy array using thr function array()


In [11]:
third_array = np.array(second_list)

Lets display this new array

In [12]:
third_array

array([[2, 3, 4],
       [5, 6, 7]])

Lets check its dimension

In [13]:
third_array.ndim

2

In [14]:
#lets check the shape
third_array.shape

(2, 3)

In [15]:
# Now lets create a list with mixed data types(integers and floats numbers)
mixed_list=[2, 2.5, 2. , 5]

In [16]:
#Lets convert this list into numpy array to examine the resulted data type:
mixed_array = np.array(mixed_list)
mixed_array

array([2. , 2.5, 2. , 5. ])

In [17]:
#lets check data types
mixed_array.dtype


dtype('float64')

We can create a numpy array with certain size filled with zero like this below

In [18]:
filled_array = np.zeros(12)
filled_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

We can create two dimensional numpy array filled with ones as below

In [19]:
one_filled_array = np.ones((4,5))
one_filled_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Thank you 
Day 2 of 30